### ISSUE TITLE
Oversettelser av gjenværende iso-koder

### ISSUE THREAD

**Issue by Phaqui** [giellatekno/new-webdict#2]
En del av iso-kodene har jeg ikke lagt inn oversettinger til. Vi har tre grensesnittspråk, nob, eng og sme, og det varier fra enhet til enhet, og fra nettleser til nettleser hvilke oversettinger Intl-biblioteket har lagret, så vi bør ha oversettinger for alle språkkoder lagret statisk i koden, slik at ikke noen opplever at det bare står en språkkode.

Denne lista ligger i src/lib/langname.js.

**Comment by Trondtr** [comment]
Her er kodane i apertium-dict:

```
uit-mac-443:apertium_dict ttr000$ pwd
/Users/ttr000/main/apps/dicts/apertium_dict
uit-mac-443:apertium_dict ttr000$ ls index_*|cut -d"." -f1|cut -d"_" -f2|tr '-' '\n'|sort|uniq|tr '\n' ' '
crk def deu eng fin fkv kom mdf myv nob ru rus sjd sje sjt sma sme smn sms swe
```


Her er kodane du har:

```
cat langname.js |grep ": {"|cut -d":" -f1|tr -d " "|sort|uniq|tr '\n' ' '
deu eng fin fit fkv kom mdf myv nob rus sjd sje sjt sma sme smj smn sms swe
```

Du manglar: crk, def, og det ser ut til at ingen av dei er relevant. I `$GTHOME/words/dicts` er det sjølvsagt mange fleire, men dei er vel ikkje relevante?

**Comment by Phaqui** [comment]
Commit e7100cdcb2275685ea6276e0d93e57aa576235ea innfører alle de jeg så manglet, untatt **chr** på nordsamisk (det var ingen wikipedia-artikkel om Cherokee på nordsamisk wikipedia).

---

Per nå genereres ordbøker fra alle ordbøker som ligger i `words/dicts` som den finner minst ei oversetting i, og det er 87 stk totalt. Lista kan sees på Azure Lab-oppsettet av sida, her: https://new-webdict--96z55xu.nicewave-ede6118a.westus2.azurecontainerapps.io/all

Det er ikke sikkert at alle skal/trenger å stå der. Da kan jeg innføre enten ei _allowlist_ (før kalt _whitelist_) over spesifikke ordbøker som skal være med - eller ei _denylist_ (før kalt _blacklist_) av ordbøker som _ikke_ skal være med, for å filtrere ut hvilke vi skal ha med - og da hvilke iso-språkkoder vi trenger oversettelser av.

Når det gjelder "def", så sier wikipedia "Dezfuli [...] is a Persian dialect spoken in Dezful in the province of Khuzestan in Iran." - og ingen av mappene i `words/dicts` inneholder den koden. Når jeg sjekker live webdict (http://gtweb.uit.no/webdict/), så ligger det språk med "def", og det er "myv-def", hvor det kun står "Эрзянь" (eller da Erzya) - og inget språk den oversetter til. Er "def" ment som en placeholder for når ei ordbok ikke er ei ordbok fra et språk til et annet - men bare ei ordliste over ord i ett enkelt språk?

**Comment by Phaqui** [comment]
Commit d8bdfa5f025a9b1d9187febca1efd49f55953f17 setter **chr** på nordsamisk til "Cherokee".

Delen om "def" anser jeg også som løst. Lukker denne, og oppretter ny for hvilke ordbøker som skal være aktive.
