### ISSUE TITLE
Teste i wiseflow

### ISSUE THREAD

**Issue by Phaqui** [giellatekno/new-webdict#3]
Et av hovedpoengene med denne ordboka, er at den er enkel, og ikke inneholder informasjon utover ordlistene. Ingen bøyinger, eksempler, osv. Dette gjør at den er ønsket brukt ved eksamen. Den nåværende versjonen av denne ordboka, "webdict", som ligger på http://gtweb.uit.no/webdict/index.html - mener jeg har vært brukt før. Den kjører også javascript, og gjør fetch() kall - slik at live bruk (på nett) ser jeg for meg at vil fungere fint.

Utfordringen er kombinasjonen flowlock-browser (FL), og ingen internett. I FL må følgende fungere: service workers, indexeddb. Studenter/elever må også på forhånd kunne åpne FL og besøke ordboka de vil bruke på eksamen, slik at den ligger lagret i FLs indexeddb.

Dette er det som må testes.

Alternative muligheter for offline-tilgjengelighet ved en eksamen, er selvfølgelig den standalone-nedlastbare utgaven av ei enkelt ordbok. Problemet der er at om FL er i bruk, så er det kanskje ikke så lett å få tilgang til filsystemet for å kunne åpne .html-dokumentet når man er inne i FL. Igjen, dette er noe man må teste.

---

I alle fall: Dette må testes og eksprimenteres med. Til dette trenger jeg:
- Å kunne opprette eksamener (eksamensadmin) i FL, for å se hvilke muligheter eksamensadministrator har når de har FL på eksamen.
- Å kunne være student som tar eksamenen. Til dette trenger jeg en maskin med windows (FL fungerer ikke på Linux).

**Comment by Trondtr** [comment]
Ideelt sett vil vi gjerne også vite om dette oppsettet er det relevante for eksaem på grunnskole og vidaregåande skole.

**Comment by Phaqui** [comment]
Oppfølging: Support-ticket er sendt til eksamensadministrasjonen.

**Comment by Phaqui** [comment]
Oppfølging: Har fått testet at alt fungerer OK i Flowlock. Om det fungerer på grunnskolers/vgs' eksmanessytemer, vet jeg ikke, og har jeg ikke mulighet til å teste ut. Lukker denne som fullført, så får vi evt komme tilbake til andre eksamenssystemer når det kommer opp.
